pipelines:
  - name: raw_patient_pipeline
    edges:
      - from: Blob_CSV1
        via: raw_patient_trigger
        to: Staging_tbl1
      - from: raw.patients
        to: ODS_tbl1
      - from: Staging_tbl1
        to: ODS_tbl1

  - name: dw_load_pipeline
    edges:
      - from: ODS_tbl1
        via: dw_load_trigger
        to: Gold_tbl1
      - from: Gold_tbl1
        to: dbo.Patients

  - name: finance_pipeline
    edges:
      - from: Blob_CSV2
        via: finance_ingest
        to: Staging_Finance
      - from: Staging_Finance
        via: finance_dw_load
        to: ODS_Finance
      - from: ODS_Finance
        to: Gold_Finance
